[project]
name = "frouros"
version = "0.1.0"
description = "A Python library for drift detection in Machine Learning problems"
license = "BSD-3-Clause"
authors = [
    {name = "Jaime Céspedes Sisniega", email = "cespedes@ifca.unican.es"}
]
maintainers = [
    {name = "Jaime Céspedes Sisniega", email = "cespedes@ifca.unican.es"}
]
readme = "README.md"
keywords = [
    "drift-detection",
    "concept-drift",
    "supervised-drift-detection",
    "unsupervised-drift-detection",
    "semi-supervised-drift-detection",
    "machine-learning"
]
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
requires-python = ">=3.8,<3.11"
dependencies = [
    "numpy>=1.23.0,<1.24",
    "requests>=2.27.0,<2.28",
    "scikit-learn>=1.0.0,<1.1",
    "scipy>=1.8.0,<1.9"
]

[project.optional-dependencies]
docs = [
    "sphinx>=4.5.0,<5.0",
    "sphinx-book-theme>=0.3.0,<0.4",
    "myst-parser>=0.18.0,<0.19",
    "myst-nb>=0.16.0,<0.17"
]

[project.urls]
repository = "https://github.com/jaime-cespedes-sisniega/frouros"

[build-system]
requires = [
    "setuptools>=60.10,<61.0",
    "wheel>=0.37.1<0.38",
    "toml>=0.10.2,<0.11",
    "build>=0.7.0,<0.8",
]
build-backend = "setuptools.build_meta"