name: Bug Report
description: Create a report to help us reproduce and correct the bug
labels: ["bug", "needs triage"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already
      addressed by searching through [the past issues](https://github.com/IFCA/frouros/issues).
- type: textarea
  attributes:
    label: Describe the bug
    description: >
      A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps/Code to Reproduce
    description: |
      Please add a minimal code example that can reproduce the error when running it. Be as succinct as possible, **do not depend on external data files**: instead you can generate synthetic data using `numpy.random`, [frouros.datasets](https://frouros.readthedocs.io/en/stable/api_reference/datasets.html) or a few lines of Python code. Example:

      ```python
      from frouros.detectors.data_drift.streaming import MMD
      import numpy as np

      np.random.seed(seed=31)
      group_A = np.random.normal(loc=1, scale=1, size=1000)
      group_B = np.concatenate(
          [
              np.random.normal(loc=1, scale=1, size=1000),
              np.random.normal(loc=5, scale=0.1, size=1000),
          ],
      )
      detector = MMD(
        chunk_size=100,
      )
      ```
    placeholder: |
      ```
      Sample code to reproduce the problem
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Results
    description: >
      Please paste or describe the expected results.
    placeholder: >
      Example: No error is thrown.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Results
    description: |
      Please paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full traceback** of the exception. For instance the code above raises the following exception:
      ```python-traceback
      ---------------------------------------------------------------------------
      Traceback (most recent call last)
        File "/frouros/mmd.py", line 12, in <module>
          detector = MMD(
      TypeError: __init__() missing 1 required positional argument: 'window_size'
      ```
    placeholder: >
      Please paste or specifically describe the actual output or traceback.
  validations:
    required: true
- type: textarea
  attributes:
    label: Python version
    render: shell
    description: |
      Please run the following and paste the output below.
      ```python
      import platform; print(f"'{platform.python_version()}'")
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Frouros version
    render: shell
    description: |
      Please run the following and paste the output below.
      ```python
      from importlib.metadata import version; version("frouros")
      ```
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉! We will review your bug report as soon as possible.
